version: "2"

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
    network_mode: host

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysqldock
#    volumes:
#      - '/opt/datasql:/var/lib/mysql'
    network_mode: host

  mongo:
    image: mongo:3.4-jessie
    ports:
      - 27017:27017
    container_name: mongo
    volumes:
      - $HOME/DB/mongo/db:/data/db
    network_mode: host

  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    network_mode: host
    volumes:
      - $HOME/DB/neo4j/data:/data
    environment:
      - NEO4J_AUTH=neo4j/root123
    container_name: neo4j

  apigateway:
    image: zuul-service
    build: zuul-gatewayservice/
    restart: always
    network_mode: host
    depends_on:
    - eurekaserver
    ports:
    - 8092:8092
    expose:
    - 8092

  eurekaserver:
    image: eureka-servcie:latest
    build: eureka-server/
    restart: always
    network_mode: host
    ports:
    - 9091:9091
    expose:
    - 9091

  configserver:
      image: config-servcie:latest
      build: config-server/
      restart: always
      network_mode: host
      ports:
      - 8888:8888
      expose:
      - 8888


  user-authentication:
    image: user-authentication-service:latest
    build: user-authentication/
    restart: always
    network_mode: host
    depends_on:
      - mysql
      - eurekaserver
      - configserver
      - apigateway
    ports:
      - 8090:8090
    expose:
      - 8090


  user-registration-service:
    image: user-registration-servcie:latest
    build: user-registration-service/
    restart: always
    network_mode: host
    depends_on:
      - eurekaserver
    ports:
      - 8015:8015
    expose:
      - 8015
#
#  mongodb:
#    image: mongo:3.4-jessie
#    container_name: "RegistrationDB"
#    ports:
#      - 27017:27017

  product-service:
    image: product-servcie:latest
    build: product-service/
    restart: always
    network_mode: host
    depends_on:
      - mongo
      - rabbitmq
      - eurekaserver
    ports:
      - 8084:8084
    expose:
      - 8084

  recommendation-service:
    image: recommendation-service:latest
    build: recommendation-service/
    restart: always
    network_mode: host
    depends_on:
      - neo4j
      - rabbitmq
      - eurekaserver
    ports:
      - 8083:8083
    expose:
      - 8083

  ontrackFrontend:
    build: OntrackFrontend/
    image: ontrack-front-end
    container_name: ontrack-front-end
    network_mode: "host"
    hostname: localhost
    ports:
      - 4200:4200
    restart: always

  products-search-service:
    image: products-search-service:latest
    build: products-search-service/
    restart: always
    network_mode: host
    depends_on:
      - mongo
      - rabbitmq
      - eurekaserver

    ports:
      - 8013:8013
    expose:
      - 8013

  stripe-payment:
    build: stripe-payment/
    image: stripe-payment:latest
    container_name: stripe-payment
    network_mode: "host"
    hostname: localhost
    ports:
      - 8014:8014
    restart: always

  sonarqube:
    image: sonarqube
    ports:
      - 9000:9000
    network_mode: host


